### ISSUE TITLE
NTC Update Bug

### ISSUE THREAD

**Issue by jidicula** [macssmcgill/Atlas#1]
When receiving command 

`@atlas ntc anat322 update 1 In Progress` when the status is already listed as "in progress", bot exits with error:

`Traceback (most recent call last):
  File "atlas.py", line 202, in <module>
    handle_command(command, channel)
  File "atlas.py", line 44, in handle_command
    new_status = re.sub(r"<b>[0-9]*</b>", "<b>" + num + "</b>", html_status)
  File "/usr/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer`

**Comment by jidicula** [comment]
I suspect it's to do with being case-sensitive. Best fix is to make everything in query lowercase, and then parse.

Test also if current status being re-requested throws this error. Also need better error handling.

**Comment by jidicula** [comment]
`@atlas NTC anat322 update 1 ready` throws identical error, so it's probably casing
